### ISSUE TITLE
German Episode/Series Names

### ISSUE THREAD

**Issue by Baine** [404d/AniDB.bundle#14]
Hey there :)

would it be possible to add support for other languages?

Specifically german would be a great improvement from my perspective,
falling back to english -> main title if german information is not available.

Thanks in advance for considering it,
and even more so for updating this in the past 👍

**Comment by 404d** [comment]
Woah there's people actually using this besides me? Sorry for the extremely late reply, I don't check Github that often.

The quick answer is... I don't think so.

The UDP API is kinda limited. While it does return German and other names if I ask for them, it doesn't seem to have any fields that will tell me which name is actually in German:
```json
{
    'other_name': [
        u'\u50d5\u3060\u3051\u304c\u3044\u306a\u3044\u8857',
        u'Erased',
        u'Erased - Die Stadt, in der es mich nicht gibt -',
        u'Desaparecido',
        u'\ub098\ub9cc\uc774 \uc5c6\ub294 \uac70\ub9ac'
    ],
    'romaji_name': u'Boku dake ga Inai Machi',
    'episodes': 12,
    'english_name': u'Erased'
}
```
Same likely goes for episode name as the structure they return is the same.


I'll keep this open as it's one of the things I do want to support, but I highly doubt it'll happen unfortunately :/

**Comment by Baine** [comment]
yeah, the api response doesn't have the language assignments.
a project I'm kind of involved with uses the .xml file that can be requested from the http api and holds the titles with language assignments.
no idea if it's possible to add something similar.

**Comment by 404d** [comment]
It's definitely possible, but I've tried keeping away from the HTTP API stuff so far. I guess there's not much of a good reason to do that though.

I might look into the HTTP API at some point. If I end up integrating it and it allows for this, I'll definitely do it. Hopefull it'll also let me solve #3 and maybe even #13. No promises on time though.

**Comment by 404d** [comment]
Then again I also really want to rip out all the existing grandfathered logic from the project this was based on, so maybe it could be wise to just start from scratch with an HTTP based one.

**Comment by Baine** [comment]
I'll close it for now, since the requested feature is a possible part of #20
